version: '2'

services:
  wordpress:
    image: esmeetup/wordpress:latest
    container_name: docker.wordpress.esmeetup.com
    depends_on:
      - mysql
    tty: true
    ports:
      - "80:80"
    networks:
      - public
      - elastic
      - database
    environment:
      WORDPRESS_DB_PASSWORD: mysqlroot

  mysql:
      image: esmeetup/mysql:latest
      container_name: docker.mysql.esmeetup.com
      tty: true
      networks:
        elastic:
        database:
            aliases:
              - mysql
      environment:
        MYSQL_ROOT_PASSWORD: mysqlroot

networks:
  public:
    external: true
  database:
    external: true
  elastic:
    external: true
